### ISSUE TITLE
TEAM manage metadata failed

### ISSUE THREAD

**Issue by alexanderlazutkin** [RoelantVos/TEAM#90] opened 2022-04-10 17:35 UTC
Starting from version 1.6.2, I encounter an error  when trying to configure metadata. Version 1.6.0 works fine for this feature. Screenshots and logs are in attachment
![1](https://user-images.githubusercontent.com/63459899/162632002-a6cf9aff-a543-4aec-ab1d-764f7b658da6.png)
![2](https://user-images.githubusercontent.com/63459899/162632011-8e7ebc79-f2ca-48c7-b20e-47ed755dbe88.png)
![3](https://user-images.githubusercontent.com/63459899/162632017-3cbd2fb5-2b37-4c79-9250-942efc879d6f.png)
[Report.wer.log](https://github.com/RoelantVos/TEAM/files/8459574/Report.wer.log)

**Comment by RoelantVos** [comment] 2022-04-10 22:42
Hi Alexander,

Thanks for reaching out. I have looked at the logs and screenshots, and did a clean install of the latest version (https://github.com/RoelantVos/TEAM/releases/tag/v1.6.4) but I can't reproduce your issue. It seems there is an exception that is not gracefully handled, but I can't see where this happens.

If you can send your metadata to my personal email (roelant@ravos.nl) I'm happy to have a look.

Kind regards,
Roelant

**Comment by alexanderlazutkin** [comment] 2022-04-12 19:11
Hi. I've sent you with subject "TEAM manage metadata failed #90"

**Comment by RoelantVos** [comment] 2022-04-14 00:57
Closing this one as resolved, no code changes.

**Closed by RoelantVos** 2022-04-14 00:57 UTC
